### ISSUE TITLE
Hamamatsu only windows

### ISSUE THREAD

**Issue by felix92** [esrf-bliss/Lima-camera-hamamatsu#1]
Hallo,
is there a reason why the hamamatsu camera can only be used on windows and not on linux?
There is also a sdk and api for linux so it should be possible to use it under linux.
Or is there an other reason?

Tanks for you answer.
Best,
Felix

**Comment by dschick** [comment]
Hi all,

I am a colleague of @felix92 and currently trying to install the lima driver for the Hamamatsu camera on Windows (11).

I installed all the lime-core dependencies via `conda` but unfortunately there is no `conda` package for this camera.
Is it maybe possible to provide that?

Alternatively, I would be very happy to get an update on the `cmake` configuration since I have multiple problems during the build process (I can post the error messages on request).

Many thanks in advance

Daniel

**Comment by laurent-claustre** [comment]
Dear Daniel,

This camera plugin was not updated since 2018 and we do not have suche device at ESRF to test.
Nevertheless I will try to update cmake and to build a conda package for windows. I do not know about the sdk version we have under sdk/, our colleagues from SOLEIL could update us? @flanglois ?
Which version of the windows sdk are you using, and which camera model?

**Comment by laurent-claustre** [comment]
Dear Daniel,
I made progress to update the hamamatsu (for windows) project and added the missing files. But I cannot compile for x64 with the SDK libraries we have under sdk/ directory, there are only compatible for x86 arch.
Do you know where I can download the latest version of the DCAMAPI sdk ?
I did find the web site dcam-api.com to download packages, but I do not well understand the difference between dcam-api and dcam-sdk ????

**Comment by steinbachfe** [comment]
Dear Laurent,
thanks for your help.
We are using the ORCA-Flash4.0 C11440-42U40.

Here is the latest SDK.

[Hamamatsu_DCAMSDK4_v22126552.zip](https://github.com/esrf-bliss/Lima-camera-hamamatsu/files/13362940/Hamamatsu_DCAMSDK4_v22126552.zip)

Many thanks
Felix

**Comment by soleil-ica** [comment]
Hi @steinbachfe, at SOLEIL, we intensivly use Hamamatsu camera (ORCA Flash, QUEST ...). we use the 64 bits Windows version of the sdk: dcamsdk4 (version 19.7). have a look here: https://github.com/soleil-ica/Lima-camera-hamamatsu . 
We do not use the Lima/python binding, nor (yet) cmake.
please do not hesitate if you have further questions.

**Comment by laurent-claustre** [comment]
Thanks @felix92, this is the sdk I did download, so I continue and hope to get soon the conda packages available on anaconda.org.
Of course I cannot test since we do not have this camera at ESRF.
Thanks @soleil-ica for your answer, so will use dcamsd4 version 22.12.6552, the latest one.

**Comment by laurent-claustre** [comment]
@soleil-ica , since dcam version 4 the API changed a lot and function names as well, where can I get your last commit/branch or what ever place to update this github project?

**Comment by soleil-ica** [comment]
@laurent-claustre , our last version is here: https://github.com/soleil-ica/Lima-camera-hamamatsu

**Comment by dschick** [comment]
Hi all,

Many thanks for all your efforts so far!

Is there anything that @felix92 and I can contribute at the moment?

Best

Daniel

**Comment by laurent-claustre** [comment]
Hi Daniel,
I've prepared a new branch 1-update-cmake-and-ci, I can push RC packages (v1.9.0rc5) on ananconda.org, but there is a bug somewhere and when I create the Camera python object python crashes due to a seg. fault error. I'm not really an expert on windows debugging tools, so if you can have an look on your side that will be great. 
The problem could be in the sip binding, so I will prepare a simple C++ test program.

You could also recompile the plugin code using VS and cmake. You do not need to compile Lima-core, just create an conda env and install the simulator (lima-camera-simulato-tango package). By the way you will get all the needed dependencies around lima-core to compile the plugin. In addition you should install in the new environment, cmake, ninja, vs2022_win-64 .

About Linux support, did you get a linux version for DCAMSDK4 ?

**Comment by dschick** [comment]
Hi @laurent-claustre ,

thanks for your efforts and description.

I do have however problems to run `cmake -Bbuild` in the root of the repo with your new branch as the DCAMSDK cannot be found.
I am also not experienced with `cmake` at all, so I was wondering if the current version of the Repo should compile as it is?

For now we once got a Linux SDK from Hamamatsu but without any support or help on fixing bugs.

Best

Daniel

**Comment by laurent-claustre** [comment]
hi @dschick 
for the sdk you have to install the conda package for the SDK called dcam-sdk4 and available on esrf-bcu channel.
to compile the lastest changes, be sure to be on the branch 1-update-cmake-and-ci . You will find the cmake command with the good parameters to pass in the file conda/camera/bld.bat.

If I've time this afternoon I will continue to debug on windows.

**Comment by laurent-claustre** [comment]
ok we find the issue, was due to a missmatch between release compilation and debug linkage.
I gonna push a new package for test on your side, version 1.9.0rc6

**Comment by laurent-claustre** [comment]
I did forget to upload the sdk package, now it is done.
you can have a look on both doc/index.rst and doc/tango.rst for some information regarding tango attributes and python plugin usage.

**Comment by dschick** [comment]
wow - thats was quick - running like a charm now!

Thanks a lot for all your help on that. This is our first Lima Device in action so we need to learn all the concepts but the camera images are streamed in the LimaViewer TangoDS perfectly well!

Best

Daniel

**Comment by laurent-claustre** [comment]
> wow - thats was quick - running like a charm now!
> 
> Thanks a lot for all your help on that. This is our first Lima Device in action so we need to learn all the concepts but the camera images are streamed in the LimaViewer TangoDS perfectly well!
> 
> Best
> 
> Daniel

Good news, do not hesitate if you need some python code example to use the tango server for advance features.

**Comment by laurent-claustre** [comment]
So I will now merge the changes and prepare an official version v1.9.0, I will also update the core documentation to have the hamamatsu doc available from lima1.readthedocs.io .

**Comment by dschick** [comment]
maybe one more (general) question:
When we start the acquisition, the camera always starts a continuous stream of frames until we actively stop it.
For our experiment, we would like to do single (software-)triggered acquisitions of a specific duration for every step in our scan.
However, we were unable to configure the Hamamatsu this way using the Lima Tango interface.
The Hamamatsu software does allow this functionality for sure.

So we are unsure if this is an issue specific to this camera plugin or a general design issue of Lima.

Many thanks in advance

Daniel

**Comment by dschick** [comment]
Short update: using the python API, everything works as expected.
In Tango, the camera also makes only a single image when setting the number of frames to 1, but the `acq_status` does change back from `running` to `ready`, after the acq has finished.

Best

Daniel

**Comment by laurent-claustre** [comment]
yes, the liveviewer device starts the camera with acq_nb_frames set to 0, this is the convention to run an infinite acquisition (when supported by the camera model).
using the LimaCCDs device you can have access to the main functionalities, set your acquisition parameters (timing, nb frames, saving, trigger mode) then call the prepareAcq() and when you are ready to start call the startAcq() command. To follow the acquistion, yes, you can read the acq_status attribute and you have counter attributes like last_image_acquired or last_image_saved (if you have activated the saving).

**Comment by dschick** [comment]
But why does the `acq_status` not automatically changes back to `ready` after a fixed number of frames?

**Comment by laurent-claustre** [comment]
yes, acq_status does, but for a fine following of the acquisition progress you could use those counters.

**Comment by dschick** [comment]
Sorry, for bothering you, I am still confused:

> yes, acq_status does
It does change or it does NOT change :)

So in our case, it only changes from `ready` to `running` after calling `startAcq` with a finite number of frames, but NOT back from `running` to `ready` after the acq has obviously finished.
It stays forever in the `running` state after a finished number of acq until we call `stopAcq`

Of course we can use the counters to determine the state, but I thought this is not the way to go for

**Comment by laurent-claustre** [comment]
Yes, it does change, acq_status is the global status, and it will change from Running to Ready once the acquisition and all the processing tasks will finish. The processing tasks  include the saving task as well.
What you observe with this camera is not normal, you should not need to call stopAcq, unless if you want to interrupt the running acquisition before the last frame.

I will have a look into the code of that camera plugin, which definitively does not follow the rules.

**Comment by dschick** [comment]
okay, thanks for the clarification.
We are currently NOT saving the images, since we only want to access it via TANGO.
So maybe this is already solving the issue.

**Comment by laurent-claustre** [comment]
but even if you do not save the images (or you do not activate any processing) the acq_status must switch to Ready once the last frame has been acquired.

**Comment by dschick** [comment]
okay, then we are on the same page!

Thank you very much for having a look into that and please let me know if and how we can help.

As I wrote above, if I use the Python API directly it seems o finish the acq correctly and does block the call just as long as the acq takes in time.

**Comment by laurent-claustre** [comment]
do you mean that the startAcq() call is blocking until the end of the acquisition?

**Comment by dschick** [comment]
Hi Laurent,

No, it is not blocking, there have been just some output which made me think that it was blocking.

So again I can confirm, that the Python API correctly handles the `acq_status`, see my test wiht `acqNbFrames = 10`:

```python
>>> ct.getStatus()
<AcquisitionStatus=AcqReady, ImageCounters=<LastImageAcquired=9, LastBaseImageReady=9, LastImageReady=9, LastImageSaved=-1, LastCounterReady=-1>
>>> ct.prepareAcq()
>>> ct.startAcq()
>>> [2023/11/30 23:58:58.994585] 25648ea6b90     *Camera*lima::Hamamatsu::Camera::CameraThread::execStartAcq (\HamamatsuCamera.cpp:1754)-Always: Allocated frames: 10
ct.getStatus()
<AcquisitionStatus=AcqRunning, ImageCounters=<LastImageAcquired=2, LastBaseImageReady=2, LastImageReady=2, LastImageSaved=-1, LastCounterReady=-1>
>>> ct.getStatus()
<AcquisitionStatus=AcqRunning, ImageCounters=<LastImageAcquired=3, LastBaseImageReady=3, LastImageReady=3, LastImageSaved=-1, LastCounterReady=-1>
>>> ct.getStatus()
<AcquisitionStatus=AcqRunning, ImageCounters=<LastImageAcquired=4, LastBaseImageReady=4, LastImageReady=4, LastImageSaved=-1, LastCounterReady=-1>
>>> ct.getStatus()
<AcquisitionStatus=AcqRunning, ImageCounters=<LastImageAcquired=5, LastBaseImageReady=5, LastImageReady=5, LastImageSaved=-1, LastCounterReady=-1>
>>> ct.getStatus()
<AcquisitionStatus=AcqRunning, ImageCounters=<LastImageAcquired=6, LastBaseImageReady=6, LastImageReady=6, LastImageSaved=-1, LastCounterReady=-1>
>>> ct.getStatus()
<AcquisitionStatus=AcqRunning, ImageCounters=<LastImageAcquired=8, LastBaseImageReady=8, LastImageReady=8, LastImageSaved=-1, LastCounterReady=-1>
>>> [2023/11/30 23:59:19.210955] 25648ea6b90     *Camera*lima::Hamamatsu::Camera::CameraThread::execStartAcq (\HamamatsuCamera.cpp:2039)-Always: --------------------------------------------------------------
[2023/11/30 23:59:19.211723] 25648ea6b90     *Camera*lima::Hamamatsu::Camera::CameraThread::execStartAcq (\HamamatsuCamera.cpp:2040)-Always: Total time (s): 20.1996
[2023/11/30 23:59:19.211723] 25648ea6b90     *Camera*lima::Hamamatsu::Camera::CameraThread::execStartAcq (\HamamatsuCamera.cpp:2041)-Always: FPS           : 0
[2023/11/30 23:59:19.211723] 25648ea6b90     *Camera*lima::Hamamatsu::Camera::CameraThread::execStartAcq (\HamamatsuCamera.cpp:2042)-Always: Lost frames   : 0
[2023/11/30 23:59:19.211723] 25648ea6b90     *Camera*lima::Hamamatsu::Camera::CameraThread::execStartAcq (\HamamatsuCamera.cpp:2043)-Always: --------------------------------------------------------------
ct.getStatus()
<AcquisitionStatus=AcqReady, ImageCounters=<LastImageAcquired=9, LastBaseImageReady=9, LastImageReady=9, LastImageSaved=-1, LastCounterReady=-1>
```

So the problem must be somewhere when mapping the `acq_status` to Tango.
I was not able to find any specific code for the Hamamatsu, since this seems to be some very general functionality of the `lima core`

Best

Daniel

**Comment by laurent-claustre** [comment]
are you reading the LimaCCDs device acq_status attribute ? This is were we map the acquisition global status:

```
    def read_acq_status(self, attr):
        status = self.__control.getStatus()
        attr.set_value(_acqstate2string(status.AcquisitionStatus))
```

**Comment by dschick** [comment]
yes, we are reading the `acq_status`, not the TangoDS `State`

Here is what jive shows after calling `preapreAcq()`:
![image](https://github.com/esrf-bliss/Lima-camera-hamamatsu/assets/13797420/4aa5c841-3745-4499-bb3c-fe24e31998b9)

And here is the case after calling `startAcq()` AND waiting for 10s - so the acq has already been finished for sure
![image](https://github.com/esrf-bliss/Lima-camera-hamamatsu/assets/13797420/f8bdddb9-08a5-4ed6-afec-e551a9261d2e)

**Comment by laurent-claustre** [comment]
Could you screen shot jive with the last_image_* attributes?  for instance last_image_acquired should change from -1 to 0 (frame number 0 if you request only 1 frame)

**Comment by dschick** [comment]
after `prepareAcq()` everything shows `-1`
![image](https://github.com/esrf-bliss/Lima-camera-hamamatsu/assets/13797420/8ba5efaf-e2ae-43f3-9fd9-c5db7f57f866)

after `startAcq()` (acq already finished) there is a change to `0` as you said:
![image](https://github.com/esrf-bliss/Lima-camera-hamamatsu/assets/13797420/6fdf4c76-96d9-44ed-b27d-9ccb56baefa3)

The attributes `ready_for_next_image` and `ready_for_next_acq` are actually working as expected and change from `True` to `False` during the acq and back to `True` when it is finished.
So for now, we could use that instead of the `acq_status` but it would be still nice to get everything properly working

Many Thanks

Daniel

**Comment by laurent-claustre** [comment]
yes, but I do not understand why when using python you get the acq_status back to Ready and not when reading the tango attr.
Pb is your are obliged to call stopAcq() otherwise the next startAcq will raise an exception.
I now suspect a cache effect on the tango side, because  atpanel is polling the attributes. Could you change in the jive "Admin" tab of the device the "Source" from CACHE_DEVICE to DEVICE ?

**Comment by dschick** [comment]
I have changed the `Source` to `Device` but nothing has changed

![image](https://github.com/esrf-bliss/Lima-camera-hamamatsu/assets/13797420/6a4753c2-734a-4c20-a992-ee9eae98a8f4)

**Comment by laurent-claustre** [comment]
reopen atkpanel or just read the acq_status from jive

**Comment by dschick** [comment]
so changing the `Source` actually makes no difference.
However, polling the `acq_status` manually in the `test device` panel or automatically via the polling settings of the `acq_status` attribute works.

So somehow jive is not polling this attribute (or caching it as you suggested) but all the others (which I have looked at so far)

I also do not have to call `stopAcq()` before calling the next `prepareAcq()` because the DS is actually in the right state.
`stopAcq()` was however updating the `acq_status()` value in jive.

In pyTango everything also runs as expected. It is obviously a jive issue or what do you think?
Jive is installed via conda btw.

Daniel

**Comment by dschick** [comment]
Forget what I was saying!

Restarting Jive solved the issue even without changing the `Source` settings

sorry for bothering you

**Comment by dschick** [comment]
I noticed kind of a related issue to the `acq_status`:

we are using `Sardana` for experimental control and data acquisiton.
In the Sardana controller we are currently polling the `acq_status` to know when the acquisition of the camera has finished.
Today, though, I noticed that we ran into problems, when we use very short integration time of about 10ms.
It seems that the `acq_status` has not been updated within that short time and sardana *sees* an `Ready` status after 10ms, because it was not changed to `Running`.

Of course I can bypass this situation within the sardana controller with some waittimes, but maybe this could be also solved in the Hamamatsu Lima plugin - or maybe this is a general issue in Lima?

Best

Daniel

**Comment by laurent-claustre** [comment]
Hi Daniel,
I would say this is normal, if sardana is onlyl polling the acq_status and the acquisition is about 10ms, there is no way for it to detect the state transitions form Ready to Running then Running to Ready, Sardana should not only poll the status but the frame counter, for instance last_image_acquired. The counters are reset to -1 after the prepareAcq and the first frame is number 0.
An other solution is that sardana subscribe to the acq_status as an event, Lima server is pushing an event when the state change.

**Comment by dschick** [comment]
okay, nice, I will apply these changes.

Thank you so much!
